"""Government authority contacts keyed by city / region (India-first, extensible)."""

from __future__ import annotations

# issue_type -> (department_name, contact_email)
IssueContacts = dict[str, tuple[str, str]]

_GCC = {
    "pothole": ("Greater Chennai Corporation — Roads", "sebrr@chennaicorporation.gov.in"),
    "garbage": ("Greater Chennai Corporation — Sanitation", "seswm@chennaicorporation.gov.in"),
    "streetlight": ("Greater Chennai Corporation — Electrical", "seelectrical@chennaicorporation.gov.in"),
    "water_leak": ("Chennai Metro Water (CMWSSB)", "cmwssb@tn.gov.in"),
    "sewage": ("Greater Chennai Corporation — Storm Water Drains", "seswd@chennaicorporation.gov.in"),
    "other": ("Greater Chennai Corporation — Commissioner", "commissioner@chennaicorporation.gov.in"),
}

_BBMP = {
    "pothole": ("BBMP — Roads & Infrastructure", "complaints@bbmp.gov.in"),
    "garbage": ("BBMP — Solid Waste Management", "swm@bbmp.gov.in"),
    "streetlight": ("BBMP — Electrical", "electrical@bbmp.gov.in"),
    "water_leak": ("BWSSB — Water Supply", "contactus@bwssb.org"),
    "sewage": ("BWSSB — Sewerage", "contactus@bwssb.org"),
    "other": ("BBMP — Control Room", "complaints@bbmp.gov.in"),
}

_BMC = {
    "pothole": ("Brihanmumbai Municipal Corporation — Roads", "customercare@mcgm.gov.in"),
    "garbage": ("BMC — Solid Waste Management", "customercare@mcgm.gov.in"),
    "streetlight": ("BMC — Electrical", "customercare@mcgm.gov.in"),
    "water_leak": ("BMC — Water Supply", "customercare@mcgm.gov.in"),
    "sewage": ("BMC — Sewerage", "customercare@mcgm.gov.in"),
    "other": ("BMC — Control Room", "customercare@mcgm.gov.in"),
}

_MCD = {
    "pothole": ("Municipal Corporation of Delhi — Roads", "mcd@mcddelhi.gov.in"),
    "garbage": ("MCD — Sanitation", "mcd@mcddelhi.gov.in"),
    "streetlight": ("MCD — Electrical", "mcd@mcddelhi.gov.in"),
    "water_leak": ("Delhi Jal Board", "djb@delhi.gov.in"),
    "sewage": ("Delhi Jal Board — Sewerage", "djb@delhi.gov.in"),
    "other": ("MCD — Control Room", "mcd@mcddelhi.gov.in"),
}

_GHMC = {
    "pothole": ("GHMC — Roads", "ghmccomplaints@ghmc.gov.in"),
    "garbage": ("GHMC — Sanitation", "ghmccomplaints@ghmc.gov.in"),
    "streetlight": ("GHMC — Electrical", "ghmccomplaints@ghmc.gov.in"),
    "water_leak": ("HMWSSB — Water", "customercare@hmwssb.gov.in"),
    "sewage": ("HMWSSB — Sewerage", "customercare@hmwssb.gov.in"),
    "other": ("GHMC — Control Room", "ghmccomplaints@ghmc.gov.in"),
}

# Primary city / corporation → department contacts by issue type
REGIONAL_CONTACTS: dict[str, IssueContacts] = {
    "chennai": _GCC,
    "bengaluru": _BBMP,
    "bangalore": _BBMP,
    "mumbai": _BMC,
    "delhi": _MCD,
    "new delhi": _MCD,
    "hyderabad": _GHMC,
    "secunderabad": _GHMC,
    "pune": {
        "pothole": ("Pune Municipal Corporation — Roads", "pmc@punecorporation.org"),
        "garbage": ("PMC — Solid Waste", "pmc@punecorporation.org"),
        "streetlight": ("PMC — Electrical", "pmc@punecorporation.org"),
        "water_leak": ("PMC — Water Supply", "pmc@punecorporation.org"),
        "sewage": ("PMC — Sewerage", "pmc@punecorporation.org"),
        "other": ("Pune Municipal Corporation", "pmc@punecorporation.org"),
    },
    "kolkata": {
        "pothole": ("Kolkata Municipal Corporation — Roads", "kmcmail@kmcgov.in"),
        "garbage": ("KMC — Sanitation", "kmcmail@kmcgov.in"),
        "streetlight": ("KMC — Electrical", "kmcmail@kmcgov.in"),
        "water_leak": ("KMC — Water Supply", "kmcmail@kmcgov.in"),
        "sewage": ("KMC — Sewerage", "kmcmail@kmcgov.in"),
        "other": ("Kolkata Municipal Corporation", "kmcmail@kmcgov.in"),
    },
    "ahmedabad": {
        "pothole": ("Ahmedabad Municipal Corporation — Roads", "amc@ahmedabadcity.gov.in"),
        "garbage": ("AMC — Sanitation", "amc@ahmedabadcity.gov.in"),
        "streetlight": ("AMC — Electrical", "amc@ahmedabadcity.gov.in"),
        "water_leak": ("AMC — Water", "amc@ahmedabadcity.gov.in"),
        "sewage": ("AMC — Sewerage", "amc@ahmedabadcity.gov.in"),
        "other": ("Ahmedabad Municipal Corporation", "amc@ahmedabadcity.gov.in"),
    },
    "surat": {
        "pothole": ("Surat Municipal Corporation — Roads", "smc@suratmunicipal.gov.in"),
        "garbage": ("SMC — Sanitation", "smc@suratmunicipal.gov.in"),
        "streetlight": ("SMC — Electrical", "smc@suratmunicipal.gov.in"),
        "water_leak": ("SMC — Water", "smc@suratmunicipal.gov.in"),
        "sewage": ("SMC — Sewerage", "smc@suratmunicipal.gov.in"),
        "other": ("Surat Municipal Corporation", "smc@suratmunicipal.gov.in"),
    },
    "jaipur": {
        "pothole": ("Jaipur Municipal Corporation — Roads", "jmcgrievance@jaipurmc.org"),
        "garbage": ("JMC — Sanitation", "jmcgrievance@jaipurmc.org"),
        "streetlight": ("JMC — Electrical", "jmcgrievance@jaipurmc.org"),
        "water_leak": ("JMC — Water", "jmcgrievance@jaipurmc.org"),
        "sewage": ("JMC — Sewerage", "jmcgrievance@jaipurmc.org"),
        "other": ("Jaipur Municipal Corporation", "jmcgrievance@jaipurmc.org"),
    },
    "lucknow": {
        "pothole": ("Lucknow Municipal Corporation — Roads", "lko@nic.in"),
        "garbage": ("LMC — Sanitation", "lko@nic.in"),
        "streetlight": ("LMC — Electrical", "lko@nic.in"),
        "water_leak": ("LMC — Water", "lko@nic.in"),
        "sewage": ("LMC — Sewerage", "lko@nic.in"),
        "other": ("Lucknow Municipal Corporation", "lko@nic.in"),
    },
    "nagpur": {
        "pothole": ("Nagpur Municipal Corporation — Roads", "nmc@nmcnagpur.gov.in"),
        "garbage": ("NMC — Sanitation", "nmc@nmcnagpur.gov.in"),
        "streetlight": ("NMC — Electrical", "nmc@nmcnagpur.gov.in"),
        "water_leak": ("NMC — Water", "nmc@nmcnagpur.gov.in"),
        "sewage": ("NMC — Sewerage", "nmc@nmcnagpur.gov.in"),
        "other": ("Nagpur Municipal Corporation", "nmc@nmcnagpur.gov.in"),
    },
    "indore": {
        "pothole": ("Indore Municipal Corporation — Roads", "imc@indorecity.gov.in"),
        "garbage": ("IMC — Sanitation", "imc@indorecity.gov.in"),
        "streetlight": ("IMC — Electrical", "imc@indorecity.gov.in"),
        "water_leak": ("IMC — Water", "imc@indorecity.gov.in"),
        "sewage": ("IMC — Sewerage", "imc@indorecity.gov.in"),
        "other": ("Indore Municipal Corporation", "imc@indorecity.gov.in"),
    },
    "bhopal": {
        "pothole": ("Bhopal Municipal Corporation — Roads", "bmc@bhopal.gov.in"),
        "garbage": ("BMC Bhopal — Sanitation", "bmc@bhopal.gov.in"),
        "streetlight": ("BMC Bhopal — Electrical", "bmc@bhopal.gov.in"),
        "water_leak": ("BMC Bhopal — Water", "bmc@bhopal.gov.in"),
        "sewage": ("BMC Bhopal — Sewerage", "bmc@bhopal.gov.in"),
        "other": ("Bhopal Municipal Corporation", "bmc@bhopal.gov.in"),
    },
    "visakhapatnam": {
        "pothole": ("GVMC — Roads", "gvmccomplaints@gvmc.gov.in"),
        "garbage": ("GVMC — Sanitation", "gvmccomplaints@gvmc.gov.in"),
        "streetlight": ("GVMC — Electrical", "gvmccomplaints@gvmc.gov.in"),
        "water_leak": ("GVMC — Water", "gvmccomplaints@gvmc.gov.in"),
        "sewage": ("GVMC — Sewerage", "gvmccomplaints@gvmc.gov.in"),
        "other": ("Greater Visakhapatnam Municipal Corporation", "gvmccomplaints@gvmc.gov.in"),
    },
    "coimbatore": {
        "pothole": ("Coimbatore City Municipal Corporation — Roads", "ccmccomplaints@ccmcorp.tn.gov.in"),
        "garbage": ("CCMC — Sanitation", "ccmccomplaints@ccmcorp.tn.gov.in"),
        "streetlight": ("CCMC — Electrical", "ccmccomplaints@ccmcorp.tn.gov.in"),
        "water_leak": ("CCMC — Water", "ccmccomplaints@ccmcorp.tn.gov.in"),
        "sewage": ("CCMC — Sewerage", "ccmccomplaints@ccmcorp.tn.gov.in"),
        "other": ("Coimbatore City Municipal Corporation", "ccmccomplaints@ccmcorp.tn.gov.in"),
    },
    "madurai": {
        "pothole": ("Madurai City Municipal Corporation — Roads", "complaints@maduraicorporation.org"),
        "garbage": ("MCMC — Sanitation", "complaints@maduraicorporation.org"),
        "streetlight": ("MCMC — Electrical", "complaints@maduraicorporation.org"),
        "water_leak": ("MCMC — Water", "complaints@maduraicorporation.org"),
        "sewage": ("MCMC — Sewerage", "complaints@maduraicorporation.org"),
        "other": ("Madurai City Municipal Corporation", "complaints@maduraicorporation.org"),
    },
    "kochi": {
        "pothole": ("Kochi Municipal Corporation — Roads", "kochicorp@kochicorp.org"),
        "garbage": ("KMC Kochi — Sanitation", "kochicorp@kochicorp.org"),
        "streetlight": ("KMC Kochi — Electrical", "kochicorp@kochicorp.org"),
        "water_leak": ("KMC Kochi — Water", "kochicorp@kochicorp.org"),
        "sewage": ("KMC Kochi — Sewerage", "kochicorp@kochicorp.org"),
        "other": ("Kochi Municipal Corporation", "kochicorp@kochicorp.org"),
    },
    "thiruvananthapuram": {
        "pothole": ("Thiruvananthapuram Municipal Corporation — Roads", "secretary@tmcofficials.in"),
        "garbage": ("TMC — Waste Management", "thiruvananthapuramtmc@gmail.com"),
        "streetlight": ("TMC — Electrical", "secretary@tmcofficials.in"),
        "water_leak": ("TMC — Water", "secretary@tmcofficials.in"),
        "sewage": ("TMC — Health / Sewerage", "ho@tmcofficials.in"),
        "other": ("Thiruvananthapuram Municipal Corporation", "secretary@tmcofficials.in"),
    },
    "trivandrum": {
        "pothole": ("Thiruvananthapuram Municipal Corporation — Roads", "secretary@tmcofficials.in"),
        "garbage": ("TMC — Waste Management", "thiruvananthapuramtmc@gmail.com"),
        "streetlight": ("TMC — Electrical", "secretary@tmcofficials.in"),
        "water_leak": ("TMC — Water", "secretary@tmcofficials.in"),
        "sewage": ("TMC — Health / Sewerage", "ho@tmcofficials.in"),
        "other": ("Thiruvananthapuram Municipal Corporation", "secretary@tmcofficials.in"),
    },
    "chandigarh": {
        "pothole": ("Chandigarh Municipal Corporation — Roads", "mcchandigarh@gov.in"),
        "garbage": ("MC Chandigarh — Sanitation", "mcchandigarh@gov.in"),
        "streetlight": ("MC Chandigarh — Electrical", "mcchandigarh@gov.in"),
        "water_leak": ("MC Chandigarh — Water", "mcchandigarh@gov.in"),
        "sewage": ("MC Chandigarh — Sewerage", "mcchandigarh@gov.in"),
        "other": ("Chandigarh Municipal Corporation", "mcchandigarh@gov.in"),
    },
    "gurugram": {
        "pothole": ("Municipal Corporation Gurugram — Roads", "grievance@mcggov.in"),
        "garbage": ("MCG — Sanitation", "grievance@mcggov.in"),
        "streetlight": ("MCG — Electrical", "grievance@mcggov.in"),
        "water_leak": ("MCG — Water", "grievance@mcggov.in"),
        "sewage": ("MCG — Sewerage", "grievance@mcggov.in"),
        "other": ("Municipal Corporation Gurugram", "grievance@mcggov.in"),
    },
    "gurgaon": {
        "pothole": ("Municipal Corporation Gurugram — Roads", "grievance@mcggov.in"),
        "garbage": ("MCG — Sanitation", "grievance@mcggov.in"),
        "streetlight": ("MCG — Electrical", "grievance@mcggov.in"),
        "water_leak": ("MCG — Water", "grievance@mcggov.in"),
        "sewage": ("MCG — Sewerage", "grievance@mcggov.in"),
        "other": ("Municipal Corporation Gurugram", "grievance@mcggov.in"),
    },
    "noida": {
        "pothole": ("Noida Authority — Roads", "grievance@noidaauthorityonline.in"),
        "garbage": ("Noida Authority — Sanitation", "grievance@noidaauthorityonline.in"),
        "streetlight": ("Noida Authority — Electrical", "grievance@noidaauthorityonline.in"),
        "water_leak": ("Noida Authority — Water", "grievance@noidaauthorityonline.in"),
        "sewage": ("Noida Authority — Sewerage", "grievance@noidaauthorityonline.in"),
        "other": ("Noida Authority", "grievance@noidaauthorityonline.in"),
    },
    "mysuru": {
        "pothole": ("Mysuru City Corporation — Roads", "mcc@mysorecity.mysuru.gov.in"),
        "garbage": ("MCC Mysuru — Sanitation", "mcc@mysorecity.mysuru.gov.in"),
        "streetlight": ("MCC Mysuru — Electrical", "mcc@mysorecity.mysuru.gov.in"),
        "water_leak": ("MCC Mysuru — Water", "mcc@mysorecity.mysuru.gov.in"),
        "sewage": ("MCC Mysuru — Sewerage", "mcc@mysorecity.mysuru.gov.in"),
        "other": ("Mysuru City Corporation", "mcc@mysorecity.mysuru.gov.in"),
    },
    "mysore": {
        "pothole": ("Mysuru City Corporation — Roads", "mcc@mysorecity.mysuru.gov.in"),
        "garbage": ("MCC Mysuru — Sanitation", "mcc@mysorecity.mysuru.gov.in"),
        "streetlight": ("MCC Mysuru — Electrical", "mcc@mysorecity.mysuru.gov.in"),
        "water_leak": ("MCC Mysuru — Water", "mcc@mysorecity.mysuru.gov.in"),
        "sewage": ("MCC Mysuru — Sewerage", "mcc@mysorecity.mysuru.gov.in"),
        "other": ("Mysuru City Corporation", "mcc@mysorecity.mysuru.gov.in"),
    },
    "vadodara": {
        "pothole": ("Vadodara Municipal Corporation — Roads", "vmc@vmc.gov.in"),
        "garbage": ("VMC — Sanitation", "vmc@vmc.gov.in"),
        "streetlight": ("VMC — Electrical", "vmc@vmc.gov.in"),
        "water_leak": ("VMC — Water", "vmc@vmc.gov.in"),
        "sewage": ("VMC — Sewerage", "vmc@vmc.gov.in"),
        "other": ("Vadodara Municipal Corporation", "vmc@vmc.gov.in"),
    },
    "patna": {
        "pothole": ("Patna Municipal Corporation — Roads", "pmc@patnanagarnigam.in"),
        "garbage": ("PMC Patna — Sanitation", "pmc@patnanagarnigam.in"),
        "streetlight": ("PMC Patna — Electrical", "pmc@patnanagarnigam.in"),
        "water_leak": ("PMC Patna — Water", "pmc@patnanagarnigam.in"),
        "sewage": ("PMC Patna — Sewerage", "pmc@patnanagarnigam.in"),
        "other": ("Patna Municipal Corporation", "pmc@patnanagarnigam.in"),
    },
    "guwahati": {
        "pothole": ("Guwahati Municipal Corporation — Roads", "gmc@gmcg.gov.in"),
        "garbage": ("GMC — Sanitation", "gmc@gmcg.gov.in"),
        "streetlight": ("GMC — Electrical", "gmc@gmcg.gov.in"),
        "water_leak": ("GMC — Water", "gmc@gmcg.gov.in"),
        "sewage": ("GMC — Sewerage", "gmc@gmcg.gov.in"),
        "other": ("Guwahati Municipal Corporation", "gmc@gmcg.gov.in"),
    },
    "bhubaneswar": {
        "pothole": ("Bhubaneswar Municipal Corporation — Roads", "bmc@bmc.gov.in"),
        "garbage": ("BMC Bhubaneswar — Sanitation", "bmc@bmc.gov.in"),
        "streetlight": ("BMC Bhubaneswar — Electrical", "bmc@bmc.gov.in"),
        "water_leak": ("BMC Bhubaneswar — Water", "bmc@bmc.gov.in"),
        "sewage": ("BMC Bhubaneswar — Sewerage", "bmc@bmc.gov.in"),
        "other": ("Bhubaneswar Municipal Corporation", "bmc@bmc.gov.in"),
    },
    "thane": {
        "pothole": ("Thane Municipal Corporation — Roads", "customercare@thanecity.gov.in"),
        "garbage": ("TMC — Sanitation", "customercare@thanecity.gov.in"),
        "streetlight": ("TMC — Electrical", "customercare@thanecity.gov.in"),
        "water_leak": ("TMC — Water", "customercare@thanecity.gov.in"),
        "sewage": ("TMC — Sewerage", "customercare@thanecity.gov.in"),
        "other": ("Thane Municipal Corporation", "customercare@thanecity.gov.in"),
    },
    "navi mumbai": {
        "pothole": ("Navi Mumbai Municipal Corporation — Roads", "nmmccomplaints@nmmconline.com"),
        "garbage": ("NMMC — Sanitation", "nmmccomplaints@nmmconline.com"),
        "streetlight": ("NMMC — Electrical", "nmmccomplaints@nmmconline.com"),
        "water_leak": ("NMMC — Water", "nmmccomplaints@nmmconline.com"),
        "sewage": ("NMMC — Sewerage", "nmmccomplaints@nmmconline.com"),
        "other": ("Navi Mumbai Municipal Corporation", "nmmccomplaints@nmmconline.com"),
    },
}

# Suburbs / districts that geocode without the main city name → parent corporation key
METRO_ALIASES: dict[str, list[str]] = {
    "chennai": [
        "guduvancheri",
        "guduvancherry",
        "urapakkam",
        "vandalur",
        "chengalpattu",
        "tambaram",
        "pallavaram",
        "chromepet",
        "avadi",
        "ambattur",
        "perungalathur",
        "selaiyur",
        "medavakkam",
        "sholinganallur",
        "velachery",
        "adyar",
        "anna nagar",
        "t nagar",
        "omr",
        "old mahabalipuram road",
    ],
    "bengaluru": [
        "whitefield",
        "electronic city",
        "marathahalli",
        "koramangala",
        "indiranagar",
        "hebbal",
        "yelahanka",
        "btm",
        "jayanagar",
        "malleshwaram",
        "rajajinagar",
        "hsr layout",
    ],
    "mumbai": [
        "andheri",
        "bandra",
        "borivali",
        "dadar",
        "powai",
        "worli",
        "colaba",
        "malad",
        "goregaon",
        "kandivali",
    ],
    "delhi": [
        "dwarka",
        "rohini",
        "saket",
        "karol bagh",
        "lajpat nagar",
        "connaught place",
        "south delhi",
        "north delhi",
        "east delhi",
        "west delhi",
    ],
    "hyderabad": [
        "gachibowli",
        "hitech city",
        "kukatpally",
        "madhapur",
        "miyapur",
        "uppal",
        "lb nagar",
        "cyberabad",
    ],
    "pune": [
        "pimpri",
        "chinchwad",
        "wakad",
        "hinjewadi",
        "kothrud",
        "baner",
        "hadapsar",
        "viman nagar",
    ],
    "kolkata": [
        "howrah",
        "salt lake",
        "rajarhat",
        "dum dum",
        "behala",
        "jadavpur",
    ],
}

# State-level fallback when city is not in the database (India)
INDIA_STATE_CONTACTS: dict[str, IssueContacts] = {
    "tamil nadu": {
        "pothole": ("Tamil Nadu Municipal Administration — Roads", "sebrr@chennaicorporation.gov.in"),
        "garbage": ("Tamil Nadu ULB — Sanitation", "seswm@chennaicorporation.gov.in"),
        "streetlight": ("Tamil Nadu ULB — Electrical", "seelectrical@chennaicorporation.gov.in"),
        "water_leak": ("Tamil Nadu Water Supply (CMWSSB)", "cmwssb@tn.gov.in"),
        "sewage": ("Tamil Nadu ULB — Storm Water Drains", "seswd@chennaicorporation.gov.in"),
        "other": ("Tamil Nadu Urban Local Bodies", "commissioner@chennaicorporation.gov.in"),
    },
    "karnataka": {
        "pothole": ("Karnataka Municipal Administration", "complaints@bbmp.gov.in"),
        "garbage": ("Karnataka ULB — Sanitation", "swm@bbmp.gov.in"),
        "streetlight": ("Karnataka ULB — Electrical", "electrical@bbmp.gov.in"),
        "water_leak": ("Karnataka Water Board", "contactus@bwssb.org"),
        "sewage": ("Karnataka ULB — Sewerage", "contactus@bwssb.org"),
        "other": ("Karnataka Urban Local Bodies", "complaints@bbmp.gov.in"),
    },
    "maharashtra": {
        "pothole": ("Maharashtra Municipal Corporation — Roads", "customercare@mcgm.gov.in"),
        "garbage": ("Maharashtra ULB — Sanitation", "customercare@mcgm.gov.in"),
        "streetlight": ("Maharashtra ULB — Electrical", "customercare@mcgm.gov.in"),
        "water_leak": ("Maharashtra Water Supply", "customercare@mcgm.gov.in"),
        "sewage": ("Maharashtra ULB — Sewerage", "customercare@mcgm.gov.in"),
        "other": ("Maharashtra Urban Local Bodies", "customercare@mcgm.gov.in"),
    },
    "telangana": {
        "pothole": ("Telangana Municipal Administration", "ghmccomplaints@ghmc.gov.in"),
        "garbage": ("Telangana ULB — Sanitation", "ghmccomplaints@ghmc.gov.in"),
        "streetlight": ("Telangana ULB — Electrical", "ghmccomplaints@ghmc.gov.in"),
        "water_leak": ("Telangana Water Board", "customercare@hmwssb.gov.in"),
        "sewage": ("Telangana ULB — Sewerage", "customercare@hmwssb.gov.in"),
        "other": ("Telangana Urban Local Bodies", "ghmccomplaints@ghmc.gov.in"),
    },
    "delhi": _MCD,
    "national capital territory of delhi": _MCD,
    "gujarat": {
        "pothole": ("Gujarat Municipal Corporation — Roads", "amc@ahmedabadcity.gov.in"),
        "garbage": ("Gujarat ULB — Sanitation", "amc@ahmedabadcity.gov.in"),
        "streetlight": ("Gujarat ULB — Electrical", "amc@ahmedabadcity.gov.in"),
        "water_leak": ("Gujarat Water Supply", "amc@ahmedabadcity.gov.in"),
        "sewage": ("Gujarat ULB — Sewerage", "amc@ahmedabadcity.gov.in"),
        "other": ("Gujarat Urban Local Bodies", "amc@ahmedabadcity.gov.in"),
    },
    "west bengal": {
        "pothole": ("West Bengal Municipal Corporation — Roads", "kmcmail@kmcgov.in"),
        "garbage": ("West Bengal ULB — Sanitation", "kmcmail@kmcgov.in"),
        "streetlight": ("West Bengal ULB — Electrical", "kmcmail@kmcgov.in"),
        "water_leak": ("West Bengal Water Supply", "kmcmail@kmcgov.in"),
        "sewage": ("West Bengal ULB — Sewerage", "kmcmail@kmcgov.in"),
        "other": ("West Bengal Urban Local Bodies", "kmcmail@kmcgov.in"),
    },
    "kerala": {
        "pothole": ("Kerala Municipal Corporation — Roads", "kochicorp@kochicorp.org"),
        "garbage": ("Kerala ULB — Sanitation", "kochicorp@kochicorp.org"),
        "streetlight": ("Kerala ULB — Electrical", "kochicorp@kochicorp.org"),
        "water_leak": ("Kerala Water Authority", "kochicorp@kochicorp.org"),
        "sewage": ("Kerala ULB — Sewerage", "kochicorp@kochicorp.org"),
        "other": ("Kerala Urban Local Bodies", "kochicorp@kochicorp.org"),
    },
    "rajasthan": {
        "pothole": ("Rajasthan Municipal Corporation — Roads", "jmcgrievance@jaipurmc.org"),
        "garbage": ("Rajasthan ULB — Sanitation", "jmcgrievance@jaipurmc.org"),
        "streetlight": ("Rajasthan ULB — Electrical", "jmcgrievance@jaipurmc.org"),
        "water_leak": ("Rajasthan Water Supply", "jmcgrievance@jaipurmc.org"),
        "sewage": ("Rajasthan ULB — Sewerage", "jmcgrievance@jaipurmc.org"),
        "other": ("Rajasthan Urban Local Bodies", "jmcgrievance@jaipurmc.org"),
    },
    "uttar pradesh": {
        "pothole": ("Uttar Pradesh Municipal Corporation — Roads", "lko@nic.in"),
        "garbage": ("UP ULB — Sanitation", "lko@nic.in"),
        "streetlight": ("UP ULB — Electrical", "lko@nic.in"),
        "water_leak": ("UP Water Supply", "lko@nic.in"),
        "sewage": ("UP ULB — Sewerage", "lko@nic.in"),
        "other": ("Uttar Pradesh Urban Local Bodies", "lko@nic.in"),
    },
    "madhya pradesh": {
        "pothole": ("Madhya Pradesh Municipal Corporation — Roads", "imc@indorecity.gov.in"),
        "garbage": ("MP ULB — Sanitation", "imc@indorecity.gov.in"),
        "streetlight": ("MP ULB — Electrical", "imc@indorecity.gov.in"),
        "water_leak": ("MP Water Supply", "imc@indorecity.gov.in"),
        "sewage": ("MP ULB — Sewerage", "imc@indorecity.gov.in"),
        "other": ("Madhya Pradesh Urban Local Bodies", "imc@indorecity.gov.in"),
    },
    "andhra pradesh": {
        "pothole": ("Andhra Pradesh Municipal Corporation — Roads", "gvmccomplaints@gvmc.gov.in"),
        "garbage": ("AP ULB — Sanitation", "gvmccomplaints@gvmc.gov.in"),
        "streetlight": ("AP ULB — Electrical", "gvmccomplaints@gvmc.gov.in"),
        "water_leak": ("AP Water Supply", "gvmccomplaints@gvmc.gov.in"),
        "sewage": ("AP ULB — Sewerage", "gvmccomplaints@gvmc.gov.in"),
        "other": ("Andhra Pradesh Urban Local Bodies", "gvmccomplaints@gvmc.gov.in"),
    },
    "punjab": {
        "pothole": ("Punjab Municipal Corporation — Roads", "mcchandigarh@gov.in"),
        "garbage": ("Punjab ULB — Sanitation", "mcchandigarh@gov.in"),
        "streetlight": ("Punjab ULB — Electrical", "mcchandigarh@gov.in"),
        "water_leak": ("Punjab Water Supply", "mcchandigarh@gov.in"),
        "sewage": ("Punjab ULB — Sewerage", "mcchandigarh@gov.in"),
        "other": ("Punjab Urban Local Bodies", "mcchandigarh@gov.in"),
    },
    "haryana": {
        "pothole": ("Haryana Municipal Corporation — Roads", "grievance@mcggov.in"),
        "garbage": ("Haryana ULB — Sanitation", "grievance@mcggov.in"),
        "streetlight": ("Haryana ULB — Electrical", "grievance@mcggov.in"),
        "water_leak": ("Haryana Water Supply", "grievance@mcggov.in"),
        "sewage": ("Haryana ULB — Sewerage", "grievance@mcggov.in"),
        "other": ("Haryana Urban Local Bodies", "grievance@mcggov.in"),
    },
    "bihar": {
        "pothole": ("Bihar Municipal Corporation — Roads", "pmc@patnanagarnigam.in"),
        "garbage": ("Bihar ULB — Sanitation", "pmc@patnanagarnigam.in"),
        "streetlight": ("Bihar ULB — Electrical", "pmc@patnanagarnigam.in"),
        "water_leak": ("Bihar Water Supply", "pmc@patnanagarnigam.in"),
        "sewage": ("Bihar ULB — Sewerage", "pmc@patnanagarnigam.in"),
        "other": ("Bihar Urban Local Bodies", "pmc@patnanagarnigam.in"),
    },
    "odisha": {
        "pothole": ("Odisha Municipal Corporation — Roads", "bmc@bmc.gov.in"),
        "garbage": ("Odisha ULB — Sanitation", "bmc@bmc.gov.in"),
        "streetlight": ("Odisha ULB — Electrical", "bmc@bmc.gov.in"),
        "water_leak": ("Odisha Water Supply", "bmc@bmc.gov.in"),
        "sewage": ("Odisha ULB — Sewerage", "bmc@bmc.gov.in"),
        "other": ("Odisha Urban Local Bodies", "bmc@bmc.gov.in"),
    },
    "assam": {
        "pothole": ("Assam Municipal Corporation — Roads", "gmc@gmcg.gov.in"),
        "garbage": ("Assam ULB — Sanitation", "gmc@gmcg.gov.in"),
        "streetlight": ("Assam ULB — Electrical", "gmc@gmcg.gov.in"),
        "water_leak": ("Assam Water Supply", "gmc@gmcg.gov.in"),
        "sewage": ("Assam ULB — Sewerage", "gmc@gmcg.gov.in"),
        "other": ("Assam Urban Local Bodies", "gmc@gmcg.gov.in"),
    },
}
